import { Footer } from "@/components/footer/footer";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { NavBar } from "@/components/navBar/navbar";
import Providers from "@/store/providers";
import AuthStore from "@/components/authStore/AuthStore";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <AuthStore>
            <NavBar />
            <hr />
            {children}
            <Footer />
          </AuthStore>
        </Providers>
      </body>
    </html>
  );
}
