import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/**/*.{js,ts,jsx,tsx}",
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/globals.css",
  ],
  theme: {
    extend: {
      backgroundImage: {
        "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
        "gradient-conic":
          "conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))",
      },
      colors: {
        MP: "#009EE3",
        PP: "#EEEEEE",
        white: "#FFFFFF",
        wine: "#c23a2e",
        wineMasOscuro: "#4c0033",
        gin: "#64bad6",
        vodka: "#e5e9f4",
        licor: "#d1cc39",
        ron: "#8c2b0e",
        whisky: "#fe9900",
        tequila: "#a0a19c",
        beige: "#EEE4B1",
        grey1: "#D8D6D7",
        grey2: "#C0BEBF",
        grey3: "#908F8F",
        grey4: "#605F60",
        grey5: "#484748",
        greyMLfilter: "#EDEDED",
        greyTextMl: "#878f9f",
        greyVivino: "#fafafa",
        blackup: "#1e1e1e",
        darkred: "#330000",
        darkblue: "#000033",
        darkgreen: "#003300",
        blueGoogle: "#0086f9",
        greenVivino: "#006b4d",
        wineMasOscuroDos: "#68091e",
        // Modo oscuro
        darkMode: {
          MP: "#005f8c",
          PP: "#BBBBBB",
          white: "#E0E0E0",
          wine: "#7a1e1a",
          wineMasOscuro: "#2b001a",
          gin: "#336a75",
          vodka: "#8c9bb7",
          licor: "#6e6d1f",
          ron: "#4b1506",
          whisky: "#994a00",
          tequila: "#4e4d48",
          beige: "#8f8961",
          grey1: "#686868",
          grey2: "#5a5959",
          grey3: "#4a4a4a",
          grey4: "#2d2d2d",
          grey5: "#1a1a1a",
          greyMLfilter: "#8a8a8a",
          greyTextMl: "#3d3f47",
          greyVivino: "#3b3b3b",
          blackup: "#121212",
          darkred: "#1a0000",
          darkblue: "#000014",
          darkgreen: "#001400",
          blueGoogle: "#00467e",
          greenVivino: "#003827",
          wineMasOscuroDos: "#26040b",
        },
      },
      fontFamily: {
        Lato: ["Lato", "sans-serif"],
        Marcellus: ["Marcellus SC", "sans-serif"],
        Alegreya: ["Alegreya Sans SC", "serif"],
        Lora: ["Lora", "sans-serif"],
        "plus-jakarta-sans": ['"Plus Jakarta Sans"', "sans-serif"],
      },
      spacing: {
        small: "1rem",
        medium: "3.5rem",
        large: "7.5rem",
      },
    },
  },
  plugins: [],
};

export default config;
